[tool.coverage.run]
branch = true
source = [ "pymonorepo_proj1" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/packages/proj1/html' --cov-report xml:'../../coverage/packages/proj1/coverage.xml' --junitxml='../../reports/packages/proj1/unittests/junit.xml' --html='../../reports/packages/proj1/unittests/html/index.html'"

[tool.poetry]
name = "pymonorepo-proj1"
version = "1.0.0"
description = "My Project 1"
authors = [ ]
license = "Proprietary"
readme = "README.md"

  [[tool.poetry.packages]]
  include = "pymonorepo_proj1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  pendulum = "^2.1.2"

    [tool.poetry.dependencies.pymonorepo-lib1]
    path = "../lib1"
    develop = true

[build-system]
requires = [ "poetry-core==1.1.0" ]
build-backend = "poetry.core.masonry.api"
