[tool.coverage.run]
branch = true
source = [ "pymonorepo_lib1" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.pytest.ini_options]
addopts = "--cov --cov-fail-under=100 --cov-report html:'../../coverage/packages/lib1/html' --cov-report xml:'../../coverage/packages/lib1/coverage.xml' --junitxml='../../reports/packages/lib1/unittests/junit.xml' --html='../../reports/packages/lib1/unittests/html/index.html'"

[tool.poetry]
name = "pymonorepo-lib1"
version = "1.0.0"
description = "My Library 1"
authors = [ ]
license = "Proprietary"
readme = "README.md"

  [[tool.poetry.packages]]
  include = "pymonorepo_lib1"

  [tool.poetry.dependencies]
  python = ">=3.8,<3.10"
  numpy = "^1.24.1"

[build-system]
requires = [ "poetry-core==1.1.0" ]
build-backend = "poetry.core.masonry.api"
